'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowRight,ArrowLeft,Check,Clock,CalendarDays,UserRound,Sparkles,CalendarPlus,MapPin,ShieldCheck,Share2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Skeleton} from '@/components/ui/skeleton';
import {useSalon} from './provider';
import {PaymentPreview} from './payment-preview';
import {addCalendar,shareAppointment} from './app';
import type {Slot,Appointment} from '@/shared/types';
import {money,dateKey,dateLabel,timeLabel} from '@/shared/theme';
export function BookingDialog(){const{booking,closeBooking}=useSalon();return <Dialog open={!!booking} onOpenChange={v=>{if(!v)closeBooking();}}>{booking&&<BookingFlow/>}</Dialog>;}
function BookingFlow(){
 const{booking,catalog,api,me,session,refresh,closeBooking,setAuthOpen,notice,go}=useSalon();const reschedule=booking?.reschedule;
 const[serviceId,setServiceId]=useState(reschedule?.service_id||booking?.serviceId||''),[professionalId,setProfessionalId]=useState(reschedule?.professional_id||booking?.professionalId||''),[unitId,setUnitId]=useState(reschedule?.unit_id||catalog.units[0]?.id||''),[extras,setExtras]=useState<string[]>(reschedule?.addons.map(a=>a.id)||[]),[date,setDate]=useState(dateKey(1)),[slots,setSlots]=useState<Slot[]>([]),[slot,setSlot]=useState<Slot|null>(null),[step,setStep]=useState(reschedule?2:0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[hold,setHold]=useState<Appointment|null>(null),[success,setSuccess]=useState<Appointment|null>(null),[now,setNow]=useState(Date.now()),[accepted,setAccepted]=useState(false),[payment,setPayment]=useState('salon'),[clientId,setClientId]=useState(booking?.clientId||''),[clients,setClients]=useState<{user_id:string;name:string}[]>([]);
 const activeHold=useRef<Appointment|null>(null);const mounted=useRef(true);const completed=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;if(activeHold.current&&!completed.current)void api.rpc('release_hold',{salon_id:catalog.salon.id,appointment_id:activeHold.current.id}).catch(()=>{});};},[api,catalog.salon.id]);
 const service=catalog.services.find(s=>s.id===serviceId);const allowedPros=catalog.professionals.filter(p=>catalog.service_professionals.some(x=>x.service_id===serviceId&&x.professional_id===p.id));const availableServices=catalog.services.filter(s=>!booking?.professionalId||catalog.service_professionals.some(x=>x.service_id===s.id&&x.professional_id===booking.professionalId));const chosenExtras=catalog.addons.filter(a=>extras.includes(a.id));const total=(service?.price_cents||0)+chosenExtras.reduce((n,a)=>n+a.price_cents,0);const duration=(service?.duration_minutes||0)+chosenExtras.reduce((n,a)=>n+a.duration_minutes,0);const seconds=hold?.hold_expires_at?Math.max(0,Math.floor((new Date(hold.hold_expires_at).getTime()-now)/1000)):0;
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(me?.memberships.some(m=>m.salon_id===catalog.salon.id&&['owner','manager','reception'].includes(m.role)))api.rpc<{clients:{user_id:string;name:string}[]}>('admin_summary',{salon_id:catalog.salon.id}).then(x=>setClients(x.clients)).catch(()=>{});},[me,api,catalog.salon.id]);
 useEffect(()=>{if(step!==2||!serviceId||!unitId)return;let active=true;setLoading(true);setSlot(null);setError('');api.rpc<Slot[]>('slots',{salon_id:catalog.salon.id,unit_id:unitId,service_id:serviceId,professional_id:professionalId,date,addons:extras,ignore_id:reschedule?.id}).then(x=>{if(active)setSlots(x);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[step,date,professionalId,serviceId,unitId,extras,api,catalog.salon.id,reschedule?.id]);
 async function reserve(){if(!slot)return;if(booking?.admin&&!reschedule&&!clientId){setError('Selecione a cliente. Para uma nova cliente, cadastre primeiro na aba Clientes.');return;}if(!session){setAuthOpen(true);return;}if(!me?.profile?.phone){closeBooking();go('profile');notice('Complete seu nome e telefone para reservar.');return;}setBusy(true);setError('');try{if(reschedule){const updated=await api.rpc<Appointment>('reschedule',{salon_id:catalog.salon.id,appointment_id:reschedule.id,starts_at:slot.starts_at});setSuccess(updated);await refresh();return;}const result=await api.rpc<Appointment>('hold',{salon_id:catalog.salon.id,unit_id:unitId,service_id:serviceId,professional_id:slot.professional_id,starts_at:slot.starts_at,addons:extras,...(clientId?{client_user_id:clientId}:{})});if(!mounted.current){await api.rpc('release_hold',{salon_id:catalog.salon.id,appointment_id:result.id});return;}activeHold.current=result;setHold(result);setAccepted(false);setStep(3);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function confirm(){if(!hold)return;setBusy(true);setError('');try{const result=await api.rpc<Appointment>('confirm',{salon_id:catalog.salon.id,appointment_id:hold.id});completed.current=true;activeHold.current=null;setSuccess(result);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function back(){if(hold){try{await api.rpc('release_hold',{salon_id:catalog.salon.id,appointment_id:hold.id});activeHold.current=null;setHold(null);}catch(e){setError((e as Error).message);return;}}setStep(Math.max(0,step-1));setError('');}
 if(success)return <DialogContent className="bella-dialog booking-dialog success-dialog"><div className="success-seal"><Check size={39} strokeWidth={1.5}/><span>✧</span></div><p className="eyebrow">UM ENCONTRO COM VOCÊ</p><DialogTitle>Seu momento<br/><em>está reservado.</em></DialogTitle><DialogDescription>Agora é só esperar pelo seu tempo de cuidado.</DialogDescription><div className="success-ticket"><span>{catalog.salon.name}</span><h3>{success.service_name}</h3><p>{dateLabel(success.starts_at,success.timezone)}</p><strong>{timeLabel(success.starts_at,success.timezone)}</strong><div className="ticket-divider"/><p>com {success.professional_name}</p><small>{success.address}</small></div><button className="btn full" onClick={()=>addCalendar(success)}><CalendarPlus size={18}/>Adicionar à minha agenda</button><button className="text-btn full" onClick={()=>shareAppointment(success,catalog.salon.name).then(message=>message&&notice(message)).catch(()=>notice('Não foi possível compartilhar. Tente novamente.'))}><Share2 size={17}/>Compartilhar confirmação</button><button className="btn outline full" onClick={()=>{closeBooking();go(booking?.admin?'admin':'agenda');}}>{booking?.admin?'Voltar à agenda do salão':'Ver meus agendamentos'}<ArrowRight size={17}/></button><p className="policy-note">{api.presentation&&payment!=='salon'?'Pagamento demonstrativo aprovado. Nenhuma cobrança realizada.':'Vai ser um prazer cuidar de você.'}</p></DialogContent>;
 return <DialogContent className="bella-dialog booking-dialog"><p className="eyebrow">{reschedule?'UM NOVO TEMPO PARA VOCÊ':'SEU MOMENTO COMEÇA AQUI'}</p><DialogTitle>{['Escolha seu cuidado','Quem vai cuidar de você?','Qual é o seu melhor momento?','Tudo pronto para o seu cuidado?'][step]}</DialogTitle><DialogDescription>{['Os detalhes fazem toda a diferença.','Escolha sua profissional ou veja todos os horários.','Horários atualizados para o cuidado que você escolheu.','Confira os detalhes antes de confirmar.'][step]}</DialogDescription><div className="booking-progress" aria-label={`Etapa ${step+1} de 4`}>{['Cuidado','Profissional','Horário','Confirmar'].map((s,i)=><span className={i<=step?'done':''} key={s}><b>{i<step?<Check size={12}/>:i+1}</b>{s}</span>)}</div>
 {step===0&&<><div className="list-stack">{availableServices.map(s=><button key={s.id} aria-pressed={serviceId===s.id} className={`selection-row ${serviceId===s.id?'selected':''}`} onClick={()=>{setServiceId(s.id);setExtras([]);if(!booking?.professionalId)setProfessionalId('');}}><span><strong>{s.name}</strong><small>{s.duration_minutes} min · {s.description}</small></span><span>{money(s.price_cents)}{serviceId===s.id?<Check size={18}/>:<ArrowRight size={17}/>}</span></button>)}</div>{service&&catalog.addons.some(a=>a.service_id===service.id)&&<div className="extras"><h3>Um carinho a mais?</h3><p>Se quiser, complete seu ritual.</p>{catalog.addons.filter(a=>a.service_id===service.id).map(a=><label className="addon-row" key={a.id}><Checkbox checked={extras.includes(a.id)} onCheckedChange={v=>setExtras(x=>v?[...x,a.id]:x.filter(y=>y!==a.id))}/><span>{a.name}<small>+ {a.duration_minutes} min</small></span><strong>+ {money(a.price_cents)}</strong></label>)}</div>}<button className="btn full" disabled={!service} onClick={()=>setStep(1)}>Escolher profissional<ArrowRight size={17}/></button></>}
 {step===1&&<><button className={`selection-row ${!professionalId?'selected':''}`} onClick={()=>setProfessionalId('')}><span><strong>Sem preferência</strong><small>Encontre o horário que combina com você</small></span><Sparkles size={21}/></button>{allowedPros.map(p=><button key={p.id} aria-pressed={professionalId===p.id} className={`selection-row ${professionalId===p.id?'selected':''}`} onClick={()=>setProfessionalId(p.id)}><span className="pro-avatar small">{p.photo_url?<img src={p.photo_url} alt=""/>:p.name[0]}</span><span className="grow"><strong>{p.name}</strong><small>{p.specialty}</small></span>{professionalId===p.id?<Check size={20}/>:<ArrowRight size={17}/>}</button>)}<button className="btn full" disabled={!allowedPros.length} onClick={()=>setStep(2)}>Encontrar horário<ArrowRight size={17}/></button></>}
 {step===2&&<><div className="booking-summary"><ScissorsIcon/><span>{service?.name}<small>{duration} min · {money(total)}</small></span></div>{catalog.units.length>1&&!reschedule&&<label className="field-label">Unidade<select value={unitId} onChange={e=>setUnitId(e.target.value)}>{catalog.units.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label>}<div className="date-strip">{Array.from({length:7},(_,i)=>dateKey(i+1)).map(d=><button aria-pressed={date===d} key={d} className={date===d?'selected':''} onClick={()=>setDate(d)}><small>{new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short'})}</small><strong>{d.slice(-2)}</strong></button>)}</div><label className="field-label">Ou escolha outra data<input aria-label="Data do agendamento" type="date" min={dateKey()} max={dateKey(catalog.settings.max_future_days)} value={date} onChange={e=>setDate(e.target.value)}/></label><p className="eyebrow">HORÁRIOS DISPONÍVEIS</p>{loading?<div className="slot-grid">{Array.from({length:8},(_,i)=><Skeleton className="slot-skeleton" key={i}/>)}</div>:slots.length?<div className="slot-grid">{slots.map(s=><button aria-pressed={slot?.starts_at===s.starts_at&&slot.professional_id===s.professional_id} key={s.starts_at+s.professional_id} className={slot?.starts_at===s.starts_at&&slot.professional_id===s.professional_id?'selected':''} onClick={()=>setSlot(s)}>{timeLabel(s.starts_at,catalog.units.find(u=>u.id===unitId)?.timezone)}{!professionalId&&<small>{s.professional_name.split(' ')[0]}</small>}</button>)}</div>:<div className="empty-state compact"><CalendarDays size={28}/><p>Não encontramos horários para esta data.</p><button className="text-btn" onClick={async()=>{if(!session){setAuthOpen(true);return;}try{await api.rpc('waitlist',{salon_id:catalog.salon.id,service_id:serviceId,date});notice('Você está na lista de espera para esta data.');}catch(e){notice((e as Error).message);}}}>Entrar na lista de espera<ArrowRight size={16}/></button></div>}{(clients.length>0||booking?.admin)&&!reschedule&&<label className="field-label">Agendar para<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">{booking?.admin?'Selecione a cliente':'Minha conta'}</option>{clients.map(c=><option value={c.user_id} key={c.user_id}>{c.name}</option>)}</select></label>}<button className="btn full" disabled={!slot||busy} onClick={reserve}>{busy?'Reservando…':reschedule?'Confirmar novo horário':session?'Continuar para confirmação':'Entrar para reservar'}<ArrowRight size={17}/></button></>}
 {step===3&&hold&&<><div className="hold-timer"><Clock size={16}/>{seconds>0?`Horário reservado por ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:'Sua reserva expirou. Volte e escolha um horário.'}</div><h3 className="detail-service">{hold.service_name}</h3>{booking?.admin&&<p>Cliente: <strong>{hold.client_name}</strong></p>}<div className="detail-line"><CalendarDays/><span>{dateLabel(hold.starts_at,hold.timezone)}<strong>{timeLabel(hold.starts_at,hold.timezone)}</strong></span></div><div className="detail-line"><UserRound/><span>{hold.professional_name}</span></div><div className="detail-line"><MapPin/><span>{hold.address}</span></div>{hold.addons.map(a=><div className="total-line" key={a.id}><span>{a.name}</span><span>{money(a.price_cents)}</span></div>)}<div className="total-line"><span>Total</span><strong>{money(hold.price_cents)}</strong></div>{api.presentation?<PaymentPreview value={payment} onChange={setPayment} amount={hold.price_cents}/>:hold.deposit_cents>0?<div className="integration-note"><strong>Sinal de {money(hold.deposit_cents)}</strong><p>O pagamento online precisa estar conectado pelo salão. Este horário ainda não foi confirmado.</p></div>:<div className="payment-option"><Check size={17}/><span>Pagar no salão<small>Nenhuma cobrança agora.</small></span></div>}<label className="addon-row"><Checkbox checked={accepted} onCheckedChange={setAccepted}/><span>Li as regras de cancelamento e reagendamento.</span></label><p className="policy-note">Cancelamentos gratuitos até {catalog.policies.cancel_hours}h antes. Reagendamentos até {catalog.policies.reschedule_hours}h antes.</p><button className="btn full" disabled={busy||!accepted||seconds<=0||(hold.deposit_cents>0&&!api.presentation)} onClick={confirm}>{busy?'Confirmando…':api.presentation&&payment!=='salon'?'Simular pagamento e confirmar':'Confirmar meu momento'}<Sparkles size={17}/></button></>}
 {error&&<p role="alert" className="form-error">{error}</p>}{step>0&&!reschedule&&<button className="text-btn" disabled={busy} onClick={back}><ArrowLeft size={16}/>Voltar</button>}<p className="booking-safe"><ShieldCheck size={13}/>Seu tempo merece cuidado.</p></DialogContent>;
}
function ScissorsIcon(){return <Sparkles size={24} strokeWidth={1.3}/>;}

