'use client';
import {useState,useEffect,useCallback} from 'react';
import {useSalon} from './provider';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Empty,download} from './app';
import {MembershipForm} from './firebase-admin-tools';
import {money,dateKey,dateLabel,timeLabel,statusLabels} from '@/shared/theme';
import type {Appointment} from '@/shared/types';
type Client={id:string;user_id:string;name:string;phone:string;notes?:string};
type Cursor={id:string;name:string}|null;

export function ClientDirectory(){
 const{api,catalog,book,notice}=useSalon();const[items,setItems]=useState<Client[]>([]),[next,setNext]=useState<Cursor>(null),[search,setSearch]=useState(''),[editing,setEditing]=useState<Client|true|null>(null),[history,setHistory]=useState<Client|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async(after:Cursor=null)=>{setBusy(true);try{const r=await api.rpc<{items:Client[];next:Cursor}>('admin_clients',{salon_id:catalog.salon.id,after});setItems(v=>after?[...v,...r.items]:r.items);setNext(r.next);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[api,catalog.salon.id]);useEffect(()=>{void load();},[load]);
 return <><div className="section-heading"><h2>Suas clientes</h2><button className="btn" onClick={()=>setEditing(true)}>Cadastrar cliente</button></div><label className="search-field"><input aria-label="Pesquisar cliente" placeholder="Nome ou telefone nas clientes carregadas" value={search} onChange={e=>setSearch(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="client-grid">{items.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(search.toLowerCase())).map(c=><article className="panel" key={c.id}><div className="profile-heading"><span className="user-avatar">{c.name[0]}</span><h3>{c.name}</h3></div><p>{c.phone}</p><small>{c.id.startsWith('guest-')?'Cadastro da recepção':'Conta vinculada ao aplicativo'}</small><div className="button-row"><button className="text-btn" onClick={()=>setEditing(c)}>Editar</button><button className="text-btn" onClick={()=>setHistory(c)}>Histórico</button><button className="btn small" onClick={()=>book({clientId:c.user_id,admin:true})}>Agendar</button></div></article>)}</div>{!items.length&&!busy&&<Empty text="Cadastre uma cliente ou compartilhe o link do salão para receber a primeira reserva."/>}{next&&<button className="btn outline" disabled={busy} onClick={()=>load(next)}>Carregar mais clientes</button>}
 <Dialog open={!!editing} onOpenChange={v=>{if(!v)setEditing(null);}}>{editing&&<DialogContent className="bella-dialog"><DialogTitle>{editing===true?'Cadastrar cliente':'Editar cliente'}</DialogTitle><DialogDescription>O cadastro da recepção permite agendar sem criar uma senha para a cliente.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api.rpc('admin_client',{salon_id:catalog.salon.id,id:editing===true?undefined:editing.id,name:f.get('name'),phone:f.get('phone'),notes:f.get('notes')});setEditing(null);await load();notice('Cliente salva.');}catch(e){notice((e as Error).message);}finally{setBusy(false);}}}><label>Nome da cliente<input required name="name" maxLength={100} defaultValue={editing===true?'':editing.name}/></label><label>Telefone com DDD<input required type="tel" name="phone" minLength={8} maxLength={30} defaultValue={editing===true?'':editing.phone}/></label><label>Observações internas<textarea name="notes" maxLength={2000} defaultValue={editing===true?'':editing.notes}/></label><button className="btn" disabled={busy}>Salvar cliente</button></form></DialogContent>}</Dialog>
 <Dialog open={!!history} onOpenChange={v=>{if(!v)setHistory(null);}}>{history&&<ClientHistory key={history.id} client={history}/>}</Dialog></>;
}
function ClientHistory({client}:{client:Client}){
 const{api,catalog}=useSalon();const[items,setItems]=useState<Appointment[]>([]),[next,setNext]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async(after?:string)=>{setBusy(true);try{const r=await api.rpc<{items:Appointment[];next:string|null}>('admin_client_history',{salon_id:catalog.salon.id,client_id:client.user_id,after});setItems(v=>after?[...v,...r.items]:r.items);setNext(r.next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[api,catalog.salon.id,client.user_id]);useEffect(()=>{void load();},[load]);
 return <DialogContent className="bella-dialog"><DialogTitle>Histórico de {client.name}</DialogTitle><DialogDescription>Agendamentos desta cliente neste salão.</DialogDescription>{error&&<p role="alert">{error}</p>}{items.map(a=><article className="notice-card" key={a.id}><div><strong>{a.service_name}</strong><p>{dateLabel(a.starts_at,a.timezone)} · {timeLabel(a.starts_at,a.timezone)}</p><span className="status">{statusLabels[a.status]}</span><p>{money(a.price_cents)} · {a.professional_name}</p>{a.review&&<p>Avaliação: {a.review.rating}/5 · {a.review.comment}</p>}</div></article>)}{!items.length&&!busy&&<p>Nenhum agendamento registrado.</p>}{next&&<button className="btn outline" disabled={busy} onClick={()=>load(next)}>Carregar mais</button>}</DialogContent>;
}

type Member={userId:string;name:string;role:string;status:string;professionalId?:string};
const roles:Record<string,string>={OWNER:'Proprietária',MANAGER:'Gerência',RECEPTIONIST:'Recepção',PROFESSIONAL:'Profissional',FINANCE:'Financeiro'};
export function TeamAccess(){
 const{api,catalog,notice}=useSalon();const[members,setMembers]=useState<Member[]>([]),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api.rpc<Member[]>('admin_members',{salon_id:catalog.salon.id}).then(setMembers).catch(e=>setError(e.message));},[api,catalog.salon.id,version]);
 return <div className="list-stack"><MembershipForm onSaved={()=>setVersion(v=>v+1)}/><section className="panel"><h2>Acessos cadastrados</h2>{error&&<p role="alert">{error}</p>}{members.map(m=><div className="selection-row" key={m.userId}><span><strong>{m.name}</strong><small>{roles[m.role]} · {m.status==='ACTIVE'?'Ativo':'Suspenso'}</small></span>{m.role!=='OWNER'&&<button className="btn small outline" disabled={busy} onClick={async()=>{setBusy(true);try{await api.rpc('admin_member',{salon_id:catalog.salon.id,user_id:m.userId,role:m.role,status:m.status==='ACTIVE'?'INACTIVE':'ACTIVE',professional_id:m.professionalId||undefined});setVersion(v=>v+1);notice('Acesso atualizado.');}catch(e){notice((e as Error).message);}finally{setBusy(false);}}}>{m.status==='ACTIVE'?'Suspender':'Reativar'}</button>}</div>)}</section></div>;
}

export function PeriodReports(){
 const{api,catalog}=useSalon();const[from,setFrom]=useState(dateKey().slice(0,8)+'01'),[to,setTo]=useState(dateKey()),[items,setItems]=useState<Appointment[]>([]),[limited,setLimited]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setError('');try{const r=await api.rpc<{items:Appointment[];limited:boolean}>('admin_reports',{salon_id:catalog.salon.id,from,to});setItems(r.items);setLimited(r.limited);}catch(e){setItems([]);setError((e as Error).message);}finally{setBusy(false);}},[api,catalog.salon.id,from,to]);useEffect(()=>{void load();},[load]);
 const completed=items.filter(a=>a.status==='COMPLETED'),revenue=completed.reduce((n,a)=>n+a.price_cents,0),byService=Object.entries(completed.reduce<Record<string,number>>((v,a)=>({...v,[a.service_name]:(v[a.service_name]||0)+a.price_cents}),{}));
 const csv=()=>{const cell=(v:string|number)=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Data','Cliente','Serviço','Profissional','Status','Valor R$'],...items.map(a=>[dateLabel(a.starts_at,a.timezone)+' '+timeLabel(a.starts_at,a.timezone),a.client_name,a.service_name,a.professional_name,statusLabels[a.status],(a.price_cents/100).toFixed(2)])];download('\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),`relatorio-${from}-${to}.csv`,'text/csv;charset=utf-8');};
 return <><h2>Resultados por período</h2><div className="admin-toolbar"><label>De<input aria-label="Início do relatório" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input aria-label="Fim do relatório" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn outline" disabled={busy||!items.length||!!error} onClick={csv}>Exportar CSV</button></div>{error&&<p role="alert" className="form-error">{error}</p>}{busy&&<p role="status">Atualizando relatório…</p>}{limited&&<p role="alert" className="form-error">O período tem mais de 1.000 agendamentos. Reduza as datas para obter o relatório completo.</p>}<div className="stats-grid">{[['Valor dos serviços concluídos',money(revenue)],['Atendimentos concluídos',String(completed.length)],['Ticket médio',money(completed.length?Math.round(revenue/completed.length):0)],['Cancelamentos',String(items.filter(a=>a.status==='CANCELLED').length)]].map(([label,value])=><section className="panel stat" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><p className="policy-note">Valores representam serviços prestados e não comprovam recebimento. Pagamento online e conciliação pelo gateway ficam para a última etapa.</p><section className="panel"><h3>Serviços realizados</h3>{byService.map(([name,value])=><div className="report-bar" key={name}><span>{name}</span><div><i style={{width:`${revenue?value/revenue*100:0}%`}}/></div><strong>{money(value)}</strong></div>)}{!byService.length&&<p>Os resultados aparecerão após os primeiros atendimentos concluídos.</p>}</section></>;
}

type Waiting={id:string;clientId:string;clientName?:string;phone?:string;service_id:string;date:string;status:string};
export function WaitingList(){
 const{api,catalog,notice}=useSalon();const[items,setItems]=useState<Waiting[]>([]),[version,setVersion]=useState(0),[error,setError]=useState('');useEffect(()=>{api.rpc<Waiting[]>('admin_waitlist',{salon_id:catalog.salon.id}).then(setItems).catch(e=>setError(e.message));},[api,catalog.salon.id,version]);
 return <section className="panel"><h2>Lista de espera</h2>{error&&<p role="alert">{error}</p>}{!items.length&&<p>Nenhuma solicitação de espera por enquanto.</p>}{items.map(w=><div className="selection-row" key={w.id}><span><strong>{w.clientName||'Cliente cadastrada'}</strong><small>{w.phone} · {catalog.services.find(s=>s.id===w.service_id)?.name||'Serviço'} · {w.date.split('-').reverse().join('/')}</small></span><label>Status<select aria-label={`Status de ${w.clientName||'solicitação'}`} value={w.status} onChange={async e=>{try{await api.rpc('admin_waitlist_status',{salon_id:catalog.salon.id,id:w.id,status:e.target.value});setVersion(v=>v+1);}catch(e){notice((e as Error).message);}}}><option value="WAITING">Aguardando</option><option value="CONTACTED">Contatada</option><option value="CLOSED">Encerrada</option></select></label></div>)}</section>;
}
