'use client';
import {useEffect,useState,useCallback} from 'react';
import {CalendarDays,Plus,Users,Scissors,Settings2,BarChart3,Link2,Copy,Download} from 'lucide-react';
import QRCode from 'qrcode';
import {useSalon} from './provider';
import {Empty,addCalendar} from './app';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {IdentitySettings,SalonSettings,type Save} from './settings';
import {ServiceEditor,ProfessionalEditor,CatalogOptions} from './catalog-editor';
import {ClientDirectory,TeamAccess,PeriodReports,WaitingList} from './business-panels';
import {dateKey,timeLabel,dateLabel,statusLabels,money} from '@/shared/theme';
import type {AdminData,Appointment,Service,Professional} from '@/shared/types';

export function BusinessAdmin(){
 const{api,catalog,me,session,setAuthOpen,book,notice,refresh}=useSalon();const member=me?.memberships.find(m=>m.salon_id===catalog.salon.id),manager=!!member&&['owner','manager'].includes(member.role),reception=!!member&&['owner','manager','reception'].includes(member.role),finance=manager||member?.role==='finance';
 const[tab,setTab]=useState('agenda'),[day,setDay]=useState(dateKey(0,catalog.units[0]?.timezone)),[filter,setFilter]=useState(''),[search,setSearch]=useState(''),[data,setData]=useState<AdminData|null>(null),[error,setError]=useState(''),[editingService,setEditingService]=useState<Service|true|null>(null),[editingPro,setEditingPro]=useState<Professional|true|null>(null),[blocking,setBlocking]=useState(false),[detail,setDetail]=useState<Appointment|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!member||member.role==='finance')return;try{setData(await api.rpc<AdminData>('admin_summary',{salon_id:catalog.salon.id,date:day}));setError('');}catch(e){setError((e as Error).message);}},[api,catalog.salon.id,day,member?.role]);
 useEffect(()=>{void load();const tick=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>clearInterval(tick);},[load]);
 const save:Save=async(action,p)=>{await api.rpc(action,{salon_id:catalog.salon.id,...p});await Promise.all([load(),refresh()]);notice('Alteração salva.');};
 useEffect(()=>{if(member?.role==='finance')setTab('reports');},[member?.role]);
 if(!session)return <Empty text="Entre com sua conta da equipe." action={<button className="btn" onClick={()=>setAuthOpen(true)}>Entrar</button>}/>;
 if(!member)return <Empty text="A proprietária precisa conceder acesso a esta conta na configuração da equipe."/>;
 const tabs=[...(member.role!=='finance'?[['agenda','Agenda',CalendarDays]]:[]),...(reception?[['clients','Clientes',Users]]:[]),...(manager?[['services','Serviços',Scissors],['team','Equipe',Users],['settings','Configurações',Settings2]]:[]),...(finance?[['reports','Resultados',BarChart3]]:[]),...(manager?[['links','Link e integrações',Link2]]:[])] as const;
 const appointments=(data?.appointments||[]).filter(a=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:a.timezone}).format(new Date(a.starts_at))===day&&(!filter||a.professional_id===filter)&&(a.client_name+' '+a.service_name).toLowerCase().includes(search.toLowerCase()));
 return <><div className="section-heading"><div className="page-heading"><p className="eyebrow">ÁREA DE ADMINISTRAÇÃO</p><h1>{member.role==='professional'?'Minha agenda profissional':catalog.salon.name}</h1><p>Agenda, equipe e configurações em um só lugar.</p></div>{reception&&<button className="btn" disabled={!catalog.published} onClick={()=>book({admin:true})}><Plus size={17}/>Novo agendamento</button>}</div>{error&&<p className="form-error" role="alert">{error}<button className="text-btn" onClick={load}>Tentar novamente</button></p>}
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="bella-tabs admin-tabs">{tabs.map(([key,label,Icon])=><TabsTrigger value={String(key)} key={String(key)}><Icon size={16}/>{String(label)}</TabsTrigger>)}</TabsList>
 <TabsContent value="agenda"><div className="admin-toolbar"><label>Data<input aria-label="Data da agenda" type="date" required value={day} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label>{member.role!=='professional'&&<label>Profissional<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas</option>{catalog.professionals.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>}<label>Pesquisar<input aria-label="Buscar na agenda" placeholder="Cliente ou serviço" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn outline" disabled={!catalog.professionals.length} onClick={()=>setBlocking(true)}>Bloquear horário</button></div><div className="day-overview"><span><strong>{appointments.filter(a=>!['CANCELLED','NO_SHOW'].includes(a.status)).length}</strong> atendimentos</span><span><strong>{appointments.filter(a=>a.status==='CHECKED_IN').length}</strong> aguardando</span><span><strong>{appointments.filter(a=>a.status==='COMPLETED').length}</strong> concluídos</span></div>
 {!data&&!error?<p role="status">Carregando agenda…</p>:!appointments.length?<Empty text="Nenhum atendimento nesta data."/>:<div className="timeline">{appointments.map(a=><article className="timeline-row" key={a.id}><time>{timeLabel(a.starts_at,a.timezone)}<small>{timeLabel(a.ends_at,a.timezone)}</small></time><div className="timeline-body"><div><span className={`status status-${a.status.toLowerCase()}`}>{statusLabels[a.status]}</span><h3>{a.client_name}</h3><p>{a.service_name} · {a.professional_name}</p></div><button className="btn small outline" onClick={()=>setDetail(a)}>Abrir atendimento</button></div></article>)}</div>}
 {(data?.blocks||[]).filter(b=>dateInZone(b.starts_at,catalog.units[0].timezone)===day).map(b=><div className="selection-row" key={b.id}><span><strong>{b.reason}</strong><small>{catalog.professionals.find(p=>p.id===b.professional_id)?.name} · {timeLabel(b.starts_at,catalog.units[0].timezone)}–{timeLabel(b.ends_at,catalog.units[0].timezone)}</small></span><button className="text-btn" disabled={busy} onClick={async()=>{if(!confirm('Liberar este intervalo para agendamentos?'))return;setBusy(true);try{await save('admin_unblock',{id:b.id});}catch(e){notice((e as Error).message);}finally{setBusy(false);}}}>Liberar intervalo</button></div>)}</TabsContent>
 <TabsContent value="clients">{reception&&<><ClientDirectory/><WaitingList/></>}</TabsContent>
 <TabsContent value="services">{manager&&<><div className="section-heading"><h2>Serviços do catálogo</h2><button className="btn" onClick={()=>setEditingService(true)}>Adicionar serviço</button></div>{catalog.services.map(s=><button className="selection-row full" key={s.id} onClick={()=>setEditingService(s)}><span><strong>{s.name}</strong><small>{s.duration_minutes} min · {catalog.service_professionals.filter(x=>x.service_id===s.id).length} profissionais habilitadas</small></span><span>{money(s.price_cents)} · Editar</span></button>)}{!catalog.services.length&&<Empty text="Adicione o primeiro serviço para abrir sua agenda."/>}<CatalogOptions save={save}/></>}</TabsContent>
 <TabsContent value="team">{manager&&<><div className="section-heading"><h2>Perfis e jornadas</h2><button className="btn" onClick={()=>setEditingPro(true)}>Adicionar profissional</button></div>{catalog.professionals.map(p=><button className="selection-row full" key={p.id} onClick={()=>setEditingPro(p)}><span><strong>{p.name}</strong><small>{p.specialty}</small></span><span>Editar perfil e horários</span></button>)}{!catalog.professionals.length&&<Empty text="Cadastre a equipe e seus horários de atendimento."/>}{member.role==='owner'&&<TeamAccess/>}</>}</TabsContent>
 <TabsContent value="settings">{manager&&<Tabs defaultValue="identity"><TabsList className="bella-tabs"><TabsTrigger value="identity">Logo e cores</TabsTrigger><TabsTrigger value="salon">Salão e horários</TabsTrigger><TabsTrigger value="rules">Regras de reserva</TabsTrigger></TabsList><TabsContent value="identity"><IdentitySettings key={catalog.salon.id} save={save}/></TabsContent><TabsContent value="salon"><SalonSettings save={save}/></TabsContent><TabsContent value="rules"><Rules save={save}/></TabsContent></Tabs>}</TabsContent>
 <TabsContent value="reports">{finance&&<PeriodReports/>}</TabsContent><TabsContent value="links">{manager&&<Links/>}</TabsContent></Tabs>
 <Dialog open={!!editingService} onOpenChange={v=>{if(!v)setEditingService(null);}}>{editingService&&<ServiceEditor value={editingService===true?undefined:editingService} save={save} close={()=>setEditingService(null)}/>}</Dialog><Dialog open={!!editingPro} onOpenChange={v=>{if(!v)setEditingPro(null);}}>{editingPro&&<ProfessionalEditor value={editingPro===true?undefined:editingPro} save={save} close={()=>setEditingPro(null)}/>}</Dialog><Dialog open={blocking} onOpenChange={setBlocking}>{blocking&&<BlockEditor day={day} save={save} close={()=>setBlocking(false)}/>}</Dialog>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}>{detail&&<StaffAppointment value={detail} canManage={reception} save={save} close={()=>setDetail(null)}/>}</Dialog></>;
}
const dateInZone=(iso:string,zone:string)=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:zone}).format(new Date(iso));
function StaffAppointment({value:a,canManage,save,close}:{value:Appointment;canManage:boolean;save:Save;close:()=>void}){
 const{book}=useSalon();const[busy,setBusy]=useState(false),[error,setError]=useState('');const next:Record<string,string>={CONFIRMED:'CHECKED_IN',CHECKED_IN:'IN_PROGRESS',IN_PROGRESS:'COMPLETED'};
 const act=async(action:string,p:Record<string,unknown>={})=>{setBusy(true);try{await save(action,{appointment_id:a.id,...p});close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <DialogContent className="bella-dialog"><DialogTitle>{a.client_name}</DialogTitle><DialogDescription>{a.service_name} com {a.professional_name}</DialogDescription><span className="status">{statusLabels[a.status]}</span><p>{dateLabel(a.starts_at,a.timezone)} · {timeLabel(a.starts_at,a.timezone)}</p><p>{a.client_phone}</p><p>{a.address}</p><strong>{money(a.price_cents)}</strong><small>Pagamento no salão</small>{error&&<p role="alert" className="form-error">{error}</p>}{next[a.status]&&<button className="btn" disabled={busy} onClick={()=>act('admin_status',{status:next[a.status]})}>{a.status==='CONFIRMED'?'Registrar chegada':a.status==='CHECKED_IN'?'Iniciar atendimento':'Concluir atendimento'}</button>}{a.status==='CONFIRMED'&&Date.parse(a.ends_at)<Date.now()&&<button className="btn outline" disabled={busy} onClick={()=>act('admin_status',{status:'NO_SHOW'})}>Registrar falta</button>}{canManage&&a.status==='CONFIRMED'&&<div className="button-row"><button className="btn outline" disabled={busy} onClick={()=>{close();book({reschedule:a,admin:true});}}>Reagendar</button><button className="text-btn danger" disabled={busy} onClick={()=>{if(confirm('Cancelar este agendamento e liberar o horário?'))void act('cancel');}}>Cancelar agendamento</button></div>}<button className="text-btn" onClick={()=>addCalendar(a)}>Adicionar ao calendário</button></DialogContent>;
}
function BlockEditor({day,save,close}:{day:string;save:Save;close:()=>void}){
 const{catalog}=useSalon();const[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <DialogContent className="bella-dialog"><DialogTitle>Bloquear horário</DialogTitle><DialogDescription>Use o horário local da unidade selecionada.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await save('admin_block',{professional_id:f.get('professional'),unit_id:f.get('unit'),local_start:f.get('start'),local_end:f.get('end'),reason:f.get('reason')});close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Profissional<select required name="professional">{catalog.professionals.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Unidade<select name="unit">{catalog.units.map(u=><option value={u.id} key={u.id}>{u.name} · {u.timezone}</option>)}</select></label><label>Início<input required name="start" type="datetime-local" defaultValue={day+'T12:00'}/></label><label>Fim<input required name="end" type="datetime-local" defaultValue={day+'T13:00'}/></label><label>Motivo<input required maxLength={200} name="reason" placeholder="Almoço, curso, folga…"/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn" disabled={busy}>Salvar bloqueio</button></form></DialogContent>;
}
function Rules({save}:{save:Save}){
 const{catalog}=useSalon();const[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel"><h2>Regras de agendamento</h2><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await save('admin_rules',Object.fromEntries([...new FormData(e.currentTarget)].map(([k,v])=>[k,Number(v)])));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div className="form-columns">{([['min_notice_minutes','Antecedência mínima (minutos)',catalog.settings.min_notice_minutes,0,10080],['max_future_days','Janela de reserva (dias)',catalog.settings.max_future_days,1,365],['cancel_hours','Cancelar até (horas antes)',catalog.policies.cancel_hours,0,720],['reschedule_hours','Reagendar até (horas antes)',catalog.policies.reschedule_hours,0,720]] as const).map(([key,label,value,min,max])=><label key={key}>{label}<input name={key} required type="number" min={min} max={max} defaultValue={value}/></label>)}</div><p>As clientes veem estas regras antes de confirmar. A recepção pode alterar reservas dentro do prazo restrito às clientes.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn" disabled={busy}>Salvar regras</button></form></section>;
}
function Links(){
 const{catalog,notice,go}=useSalon();const[url,setUrl]=useState(''),[qr,setQr]=useState('');useEffect(()=>{const link=new URL('/',location.origin);link.searchParams.set('salon',catalog.salon.slug);setUrl(link.href);QRCode.toDataURL(link.href,{width:320,margin:2}).then(setQr).catch(e=>notice(e.message));},[catalog.salon.slug,notice]);
 return <><section className="panel share-panel">{qr&&<img src={qr} alt="QR code do salão"/>}<div><h2>Compartilhe seu salão</h2><p>{catalog.published?'Seu salão está publicado e pronto para receber reservas.':'Publique o salão nas configurações para liberar o acesso das clientes.'}</p><code className="share-url">{url}</code><div className="button-row"><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(url);notice('Link copiado.');}catch{notice('Copie o endereço exibido.');}}}><Copy size={16}/>Copiar link</button>{qr&&<a className="btn outline" href={qr} download="qr-salao.png"><Download size={16}/>Baixar QR</a>}<a className="text-btn" href={url} target="_blank" rel="noreferrer">Abrir link</a></div></div></section><section className="panel"><h2>Integrações e notificações</h2>{[['Firebase','Autenticação, agenda e imagens conectadas'],['Notificações push','Disponíveis; ativação individual no perfil'],['WhatsApp oficial','Integração reservada para a última etapa'],['Pagamento online','Gateway reservado para a última etapa']].map(([name,status])=><div className="integration-row" key={name}><strong>{name}</strong><span>{status}</span></div>)}<button className="btn outline" onClick={()=>go('profile')}>Configurar notificações neste aparelho</button></section></>;
}
