'use client';
import {useState} from 'react';
import {useSalon} from './provider';
import {DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ImageField,ScheduleFields,defaultSchedule,type Save} from './settings';
import type {Service,Professional} from '@/shared/types';
import {money} from '@/shared/theme';

export function ServiceEditor({value,save,close}:{value?:Service;save:Save;close:()=>void}){
 const{catalog}=useSalon();const[selected,setSelected]=useState(catalog.service_professionals.filter(x=>x.service_id===value?.id).map(x=>x.professional_id)),[image,setImage]=useState(value?.image_url||''),[uploading,setUploading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <DialogContent className="bella-dialog"><DialogTitle>{value?'Editar serviço':'Adicionar serviço'}</DialogTitle><DialogDescription>Defina o cuidado, seu preço e as profissionais que podem atendê-lo.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await save('admin_service',{id:value?.id,name:f.get('name'),description:f.get('description'),category_id:f.get('category'),duration_minutes:Number(f.get('duration')),cleanup_minutes:Number(f.get('cleanup')),price_cents:Math.round(Number(f.get('price'))*100),deposit_cents:value?.deposit_cents||0,professional_ids:selected,image_url:image});close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <label>Nome do serviço<input name="name" required maxLength={100} defaultValue={value?.name}/></label><label>Descrição<textarea name="description" maxLength={1000} defaultValue={value?.description}/></label><label>Categoria<select name="category" defaultValue={value?.category_id}>{catalog.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-columns"><label>Duração (min)<input name="duration" type="number" required min={5} max={600} defaultValue={value?.duration_minutes||60}/></label><label>Intervalo de limpeza (min)<input name="cleanup" type="number" required min={0} max={120} defaultValue={value?.cleanup_minutes??0}/></label><label>Preço (R$)<input name="price" type="number" required min={0} step="0.01" defaultValue={(value?.price_cents||0)/100}/></label></div>
 <p className="policy-note">Pagamento no salão. O sinal online será configurado junto com o gateway.{!!value?.deposit_cents&&` Este serviço já exige sinal de ${money(value.deposit_cents)}; retire-o na configuração antes de testar.`}</p>
 <fieldset><legend>Profissionais habilitadas</legend>{catalog.professionals.map(p=><label className="switch-row" key={p.id}><span>{p.name}</span><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/></label>)}{!catalog.professionals.length&&<p>Cadastre uma profissional na aba Equipe primeiro.</p>}</fieldset><ImageField onBusy={setUploading} label="Foto do serviço" value={image} onChange={setImage}/>
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="btn" disabled={busy||uploading||!selected.length}>{busy?'Salvando…':'Salvar serviço'}</button>{value&&<button type="button" className="text-btn danger" disabled={busy} onClick={async()=>{if(!confirm('Retirar este serviço do catálogo? Agendamentos existentes serão mantidos.'))return;setBusy(true);try{await save('admin_remove',{id:value.id,kind:'services'});close();}catch(e){setError((e as Error).message);setBusy(false);}}}>Retirar serviço do catálogo</button>}</form></DialogContent>;
}

export function ProfessionalEditor({value,save,close}:{value?:Professional;save:Save;close:()=>void}){
 const{catalog}=useSalon();const[unit,setUnit]=useState(value?.schedules?.[0]?.unit_id||catalog.units[0]?.id||''),[schedule,setSchedule]=useState(value?.schedules?.[0]||defaultSchedule),[photo,setPhoto]=useState(value?.photo_url||''),[uploading,setUploading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <DialogContent className="bella-dialog"><DialogTitle>{value?'Editar profissional':'Adicionar profissional'}</DialogTitle><DialogDescription>O perfil público e a jornada determinam os horários disponíveis.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await save('admin_professional',{id:value?.id,name:f.get('name'),specialty:f.get('specialty'),bio:f.get('bio'),photo_url:photo,...schedule,unit_id:unit});close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Nome da profissional<input name="name" required maxLength={100} defaultValue={value?.name}/></label><label>Especialidade<input name="specialty" maxLength={150} defaultValue={value?.specialty}/></label><label>Sobre a profissional<textarea name="bio" maxLength={1000} defaultValue={value?.bio}/></label><ImageField onBusy={setUploading} label="Foto da profissional" value={photo} onChange={setPhoto}/><label>Jornada da unidade<select value={unit} onChange={e=>{setUnit(e.target.value);setSchedule(value?.schedules?.find(s=>s.unit_id===e.target.value)||defaultSchedule);}}>{catalog.units.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><ScheduleFields value={schedule} onChange={setSchedule}/><p className="policy-note">A disponibilidade respeita também o funcionamento e os intervalos da unidade. Para conceder acesso ao aplicativo, use Acessos da equipe.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn" disabled={busy||uploading}>{busy?'Salvando…':'Salvar profissional'}</button>{value&&<button type="button" className="text-btn danger" disabled={busy} onClick={async()=>{if(!confirm('Retirar esta profissional do catálogo? Os atendimentos existentes serão preservados.'))return;setBusy(true);try{await save('admin_remove',{kind:'professionals',id:value.id});close();}catch(e){setError((e as Error).message);setBusy(false);}}}>Retirar profissional do catálogo</button>}</form></DialogContent>;
}

export function CatalogOptions({save}:{save:Save}){
 const{catalog,notice}=useSalon();const[category,setCategory]=useState(''),[editing,setEditing]=useState(''),[busy,setBusy]=useState(false),[addon,setAddon]=useState<string|null>(null);
 const extra=catalog.addons.find(a=>a.id===addon);
 const remove=async(kind:string,id:string)=>{if(!confirm('Remover este item do catálogo?'))return;setBusy(true);try{await save('admin_remove',{kind,id});}catch(e){notice((e as Error).message);}finally{setBusy(false);}};
 return <div className="list-stack"><section className="panel"><h2>Categorias dos serviços</h2><div className="category-management">{catalog.categories.map(c=><div key={c.id}><button className="text-btn" onClick={()=>{setEditing(c.id);setCategory(c.name);}}>{c.name}</button><button className="icon-btn" aria-label={`Remover categoria ${c.name}`} disabled={busy} onClick={()=>remove('categories',c.id)}>×</button></div>)}</div><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await save('admin_category',{id:editing||undefined,name:category});setEditing('');setCategory('');}catch(e){notice((e as Error).message);}finally{setBusy(false);}}}><label>{editing?'Editar categoria':'Nova categoria'}<input required maxLength={60} value={category} onChange={e=>setCategory(e.target.value)}/></label><div className="button-row"><button className="btn" disabled={busy}>Salvar categoria</button>{editing&&<button className="text-btn" type="button" onClick={()=>{setEditing('');setCategory('');}}>Cancelar edição</button>}</div></form></section>
 <section className="panel"><div className="section-heading"><h2>Extras dos serviços</h2><button className="btn outline" disabled={!catalog.services.length} onClick={()=>setAddon('new')}>Adicionar extra</button></div><p>Extras são opcionais na reserva e somam preço e duração ao serviço.</p>{catalog.addons.map(a=><div className="selection-row" key={a.id}><button className="text-btn" onClick={()=>setAddon(a.id)}>{a.name} · {money(a.price_cents)} · {a.duration_minutes} min</button><button className="icon-btn" aria-label={`Remover extra ${a.name}`} disabled={busy} onClick={()=>remove('addons',a.id)}>×</button></div>)}{!catalog.addons.length&&<p>Nenhum extra cadastrado.</p>}{addon&&<form key={addon} className="form-stack inset-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await save('admin_addon',{id:extra?.id,name:f.get('name'),service_id:f.get('service'),duration_minutes:Number(f.get('minutes')),price_cents:Math.round(Number(f.get('price'))*100)});setAddon(null);}catch(e){notice((e as Error).message);}finally{setBusy(false);}}}><label>Nome do extra<input required name="name" defaultValue={extra?.name}/></label><label>Serviço<select name="service" defaultValue={extra?.service_id}>{catalog.services.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Duração adicional (min)<input name="minutes" type="number" min={0} max={120} required defaultValue={extra?.duration_minutes||0}/></label><label>Valor adicional (R$)<input name="price" type="number" step="0.01" min={0} required defaultValue={(extra?.price_cents||0)/100}/></label><div className="button-row"><button className="btn" disabled={busy}>Salvar extra</button><button type="button" className="text-btn" onClick={()=>setAddon(null)}>Cancelar</button></div></form>}</section></div>;
}
