'use client';
import {useCallback,useEffect,useState} from 'react';
import {useSalon} from './provider';
import {money} from '@/shared/theme';
import type {Appointment} from '@/shared/types';

type Charge={id:string;status:string;invoiceUrl:string|null;valueCents?:number;value?:number;appointmentId?:string;outcome?:string;appointment?:Appointment};
type FinancialStatus={configured:boolean;environment:string;monthlyCents:number|null;account:null|{id:string;status:string;ownerName:string;payout?:Record<string,unknown>};subscription:null|{id:string;status:string;monthlyCents:number;invoiceUrl:string|null;paidThrough:string|null};payments:Charge[];transfers:{id:string;status:string;valueCents:number;date:string}[]};
const labels:Record<string,string>={PENDING:'Pendente',APPROVED:'Aprovada',AWAITING_APPROVAL:'Em análise',REJECTED:'Dados recusados',CONFIRMED:'Pagamento confirmado',RECEIVED:'Recebido',OVERDUE:'Vencido',REFUNDED:'Estornado',REFUND_REQUESTED:'Estorno solicitado',REFUND_IN_PROGRESS:'Estorno em andamento',PARTIALLY_REFUNDED:'Estorno parcial',REFUND_REQUIRED:'Reembolso necessário',AWAITING_PAYMENT:'Aguardando pagamento',ACTIVE:'Ativa',CANCELLED:'Cancelada',DONE:'Concluído',FAILED:'Falhou',UNCERTAIN:'Conferência necessária',PROCESSING:'Processando'};
const label=(s:string)=>labels[s]||s;
function PayerFields(){return <div className="form-columns"><label>Nome do titular<input name="name" required maxLength={100} autoComplete="name"/></label><label>E-mail<input name="email" required type="email" autoComplete="email"/></label><label>CPF ou CNPJ<input name="cpfCnpj" required inputMode="numeric" maxLength={18}/></label><label>Celular<input name="mobilePhone" required type="tel" autoComplete="tel"/></label></div>;}
const fields=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form).entries());

export function CustomerPaymentHistory(){
 const{api,catalog,refresh}=useSalon();const[items,setItems]=useState<Charge[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(()=>api.rpc<Charge[]>('asaas_my_payments',{salon_id:catalog.salon.id}).then(setItems).catch(e=>setError(e.message)),[api,catalog.salon.id]);
 useEffect(()=>{void load();},[load]);
 if(!items.length)return error?<p className="policy-note">Não foi possível carregar os pagamentos. <button className="text-btn" onClick={load}>Tentar novamente</button></p>:null;
 return <section className="panel"><h2>Meus pagamentos</h2>{items.map(p=><div className="integration-row" key={p.id}><div><strong>{money(p.valueCents||0)}</strong><p>{label(p.status)}</p>{p.outcome==='REFUND_REQUIRED'&&<p>Reembolso em análise pelo salão. O pagamento não garante um horário expirado.</p>}</div><div className="button-row">{p.invoiceUrl&&<a className="text-btn" href={p.invoiceUrl} target="_blank" rel="noreferrer">Abrir cobrança</a>}<button className="text-btn" disabled={busy} onClick={async()=>{setBusy(true);try{await api.rpc('asaas_payment_sync',{salon_id:catalog.salon.id,payment_id:p.id});await load();await refresh();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Conferir pagamento</button></div></div>)}{error&&<p role="alert">{error}</p>}</section>;
}

export function SalonPayments(){
 const{api,catalog,me,notice}=useSalon();const owner=me?.memberships.some(m=>m.salon_id===catalog.salon.id&&m.role==='owner');
 const[data,setData]=useState<FinancialStatus|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[balance,setBalance]=useState<number|null>(null);
 const rpc=useCallback(<T,>(action:string,p:Record<string,unknown>={})=>api.rpc<T>(action,{salon_id:catalog.salon.id,...p}),[api,catalog.salon.id]);
 const load=useCallback(async()=>{try{setData(await rpc<FinancialStatus>('asaas_status'));setError('');}catch(e){setError((e as Error).message);}},[rpc]);
 useEffect(()=>{void load();},[load]);
 const act=async(action:string,p:Record<string,unknown>={})=>{setBusy(true);setError('');try{const result=await rpc<{balanceCents?:number}>(action,p);if(result.balanceCents!==undefined)setBalance(result.balanceCents);await load();notice('Informações atualizadas.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="form-stack"><section className="panel"><h2>Pagamentos e mensalidade</h2><p>Mensalidade do sistema, pagamentos dos atendimentos e repasses para a conta do salão.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="text-btn" disabled={busy} onClick={load}>Atualizar informações</button>{!data?<p>Carregando dados financeiros…</p>:<p className="policy-note">{data.configured?data.environment==='sandbox'?'Ambiente de testes Asaas. As operações não movimentam dinheiro real.':'Asaas em produção.':'Ativação pendente: a plataforma precisa configurar a conta Asaas e a integração segura.'}</p>}</section>
 {data&&<><section className="panel"><h2>Mensalidade do sistema</h2><p>{data.monthlyCents?`${money(data.monthlyCents)} por mês`:'O valor do plano será definido pela plataforma.'}</p>{data.subscription?<><p>Situação: <strong>{label(data.subscription.status)}</strong></p>{data.subscription.paidThrough&&<p>Período pago até {data.subscription.paidThrough}</p>}{data.subscription.invoiceUrl&&<a className="btn" target="_blank" rel="noreferrer" href={data.subscription.invoiceUrl}>Pagar mensalidade no Asaas</a>}{owner&&<div className="button-row"><button className="btn outline" disabled={busy} onClick={()=>act('asaas_subscription_sync')}>Conferir mensalidade</button>{data.subscription.status!=='CANCELLED'&&<button className="text-btn danger" disabled={busy} onClick={()=>{if(confirm('Cancelar a renovação da mensalidade do sistema?'))void act('asaas_subscription_cancel');}}>Cancelar renovação</button>}</div>}</>:owner&&<form className="form-stack" onSubmit={e=>{e.preventDefault();const f=fields(e.currentTarget);void act('asaas_subscription_create',{payer:f,billingType:f.billingType});}}><PayerFields/><label>Pagamento<select name="billingType"><option value="CREDIT_CARD">Cartão de crédito recorrente</option><option value="PIX">Pix — pagar a cobrança a cada mês</option></select></label><p className="policy-note">O cartão é informado na página segura do Asaas. No Pix mensal, cada cobrança precisa ser paga.</p><button className="btn" disabled={busy||!data.configured||!data.monthlyCents}>Contratar mensalidade</button></form>}</section>
 <section className="panel"><h2>Conta de recebimentos do salão</h2>{data.account?<><p>{data.account.ownerName} · <strong>{label(data.account.status)}</strong></p><p>Conclua a ativação e o envio dos documentos na conta Asaas do salão.</p><a className="text-btn" href={data.environment==='sandbox'?'https://sandbox.asaas.com':'https://www.asaas.com'} target="_blank" rel="noreferrer">Abrir Asaas</a>{owner&&<button className="btn outline" disabled={busy||!data.configured} onClick={()=>act('asaas_account_sync')}>Conferir aprovação e saldo</button>}{balance!==null&&<p>Saldo disponível: <strong>{money(balance)}</strong></p>}</>:owner&&<form className="form-stack" onSubmit={e=>{e.preventDefault();const f=fields(e.currentTarget);if(!f.birthDate)delete f.birthDate;if(!f.companyType)delete f.companyType;void act('asaas_account_create',{account:{...f,incomeValue:Number(f.incomeValue)}});}}><PayerFields/><div className="form-columns"><label>Tipo de empresa<select name="companyType"><option value="">Pessoa física</option><option value="MEI">MEI</option><option value="LIMITED">Limitada</option><option value="INDIVIDUAL">Empresário individual</option><option value="ASSOCIATION">Associação</option></select></label><label>Nascimento (pessoa física)<input name="birthDate" type="date"/></label><label>Receita mensal estimada (R$)<input name="incomeValue" type="number" min="1" step="0.01" required/></label><label>CEP<input name="postalCode" required maxLength={9}/></label><label>Endereço<input name="address" required maxLength={150}/></label><label>Número<input name="addressNumber" required maxLength={20}/></label><label>Bairro<input name="province" required maxLength={100}/></label></div><p className="policy-note">Ao continuar, o Asaas criará a conta do titular e enviará o convite de ativação ao e-mail informado. O recebimento depende da aprovação cadastral.</p><button className="btn" disabled={busy||!data.configured}>Criar conta Asaas do salão</button></form>}</section>
 {owner&&data.account&&<PayoutSettings key={data.account.id+JSON.stringify(data.account.payout)} initial={data.account.payout} disabled={busy||!data.configured} save={settings=>act('asaas_payout_save',{settings})}/>}
 <section className="panel"><h2>Pagamentos dos atendimentos</h2>{!data.payments.length?<p>Nenhuma cobrança registrada.</p>:data.payments.map(p=><div className="integration-row" key={p.id}><div><strong>{money(p.valueCents||0)}</strong><p>{label(p.status)}{p.outcome==='REFUND_REQUIRED'?' · Reembolso necessário: reserva indisponível':''}</p><small>{p.id}</small></div><div className="button-row"><button className="text-btn" disabled={busy} onClick={()=>act('asaas_payment_sync',{payment_id:p.id})}>Conferir</button>{p.invoiceUrl&&<a className="text-btn" href={p.invoiceUrl} target="_blank" rel="noreferrer">Ver cobrança</a>}{owner&&['CONFIRMED','RECEIVED'].includes(p.status)&&<button className="text-btn danger" disabled={busy} onClick={()=>{if(confirm(`Solicitar estorno integral de ${money(p.valueCents||0)}? O Asaas processará a devolução conforme o saldo e as regras da transação.`))void act('asaas_refund',{payment_id:p.id});}}>Estornar</button>}</div></div>)}</section>
 <section className="panel"><h2>Histórico de repasses</h2>{!data.transfers.length?<p>Nenhum repasse executado.</p>:data.transfers.map(t=><div className="integration-row" key={t.id}><span>{t.date}</span><strong>{money(t.valueCents||0)}</strong><span>{label(t.status)}</span></div>)}</section></>}
 </div>;
}
function PayoutSettings({initial={},disabled,save}:{initial?:Record<string,unknown>;disabled:boolean;save:(p:Record<string,unknown>)=>void}){
 const p=initial as {enabled?:boolean;frequency?:string;weekday?:number;monthday?:number;reserveCents?:number;minimumCents?:number;bankAccount?:{bank:{code:string};ownerName:string;cpfCnpj:string;agency:string;account:string;accountDigit:string;bankAccountType:string}};const b=p.bankAccount;
 return <section className="panel"><h2>Repasse programado para seu banco</h2><p>Transferimos o saldo disponível, descontando o valor que você decidir manter na conta Asaas. Valores de cartão ainda não liberados entram nos próximos repasses.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=fields(e.currentTarget);save({enabled:f.enabled==='on',frequency:f.frequency,weekday:Number(f.weekday),monthday:Number(f.monthday),reserveCents:Math.round(Number(f.reserve)*100),minimumCents:Math.round(Number(f.minimum)*100),bankAccount:{bank:{code:f.bank},ownerName:f.ownerName,cpfCnpj:f.cpfCnpj,agency:f.agency,account:f.account,accountDigit:f.accountDigit,bankAccountType:f.bankAccountType}});}}><div className="form-columns"><label>Frequência<select name="frequency" defaultValue={p.frequency||'WEEKLY'}><option value="DAILY">Diária</option><option value="WEEKLY">Semanal</option><option value="MONTHLY">Mensal</option></select></label><label>Dia da semana (se semanal)<select name="weekday" defaultValue={p.weekday||1}>{['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'].map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select></label><label>Dia do mês (se mensal)<input name="monthday" type="number" min="1" max="28" required defaultValue={p.monthday||1}/></label><label>Manter no Asaas (R$)<input name="reserve" type="number" step="0.01" min="0" required defaultValue={(p.reserveCents??10000)/100}/></label><label>Repasse mínimo (R$)<input name="minimum" type="number" step="0.01" min="1" required defaultValue={(p.minimumCents??1000)/100}/></label><label>Código do banco (3 dígitos)<input name="bank" pattern="[0-9]{3}" required defaultValue={b?.bank.code}/></label><label>Nome do titular<input name="ownerName" required defaultValue={b?.ownerName}/></label><label>CPF/CNPJ do titular<input name="cpfCnpj" required defaultValue={b?.cpfCnpj}/></label><label>Agência sem dígito<input name="agency" required pattern="[0-9]+" defaultValue={b?.agency}/></label><label>Conta sem dígito<input name="account" required pattern="[0-9]+" defaultValue={b?.account}/></label><label>Dígito da conta<input name="accountDigit" required defaultValue={b?.accountDigit}/></label><label>Tipo<select name="bankAccountType" defaultValue={b?.bankAccountType||'CONTA_CORRENTE'}><option value="CONTA_CORRENTE">Corrente</option><option value="CONTA_POUPANCA">Poupança</option></select></label></div><label className="addon-row"><input type="checkbox" name="enabled" defaultChecked={p.enabled}/><span>Autorizo repasses programados para esta conta do mesmo titular do salão.</span></label><p className="policy-note">Execução a partir das 9h, horário de Brasília. O Asaas pode exigir autorização adicional. Transferências só aparecem como concluídas após confirmação.</p><button className="btn" disabled={disabled}>Salvar programação</button></form></section>;
}

export function OnlineCheckout({hold,accepted,onPaid,onStarted}:{hold:Appointment;accepted:boolean;onPaid:(a:Appointment)=>void;onStarted:()=>void}){
 const{api,catalog}=useSalon();const[charge,setCharge]=useState<Charge|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rpc=<T,>(action:string,p:Record<string,unknown>)=>api.rpc<T>(action,{salon_id:catalog.salon.id,...p});
 async function check(){if(!charge)return;setBusy(true);try{const r=await rpc<Charge>('asaas_payment_sync',{payment_id:charge.id});setCharge(r);if(r.appointment&&r.appointment.status==='CONFIRMED')onPaid(r.appointment);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="form-stack"><h3>{hold.deposit_cents?`Pagar sinal de ${money(hold.deposit_cents)}`:`Pagar ${money(hold.price_cents)} online`}</h3>{charge?<><p>{label(charge.status)}</p>{charge.outcome==='REFUND_REQUIRED'?<p role="alert">O pagamento foi recebido após o prazo da reserva. O horário não foi confirmado. O salão foi sinalizado para tratar o reembolso.</p>:<><p>Abra o checkout seguro para pagar. O horário fica reservado por até 15 minutos a partir da criação da cobrança.</p>{charge.invoiceUrl&&<a className="btn" target="_blank" rel="noreferrer" href={charge.invoiceUrl}>Pagar no Asaas</a>}<button type="button" className="btn outline" disabled={busy} onClick={check}>Conferir pagamento e agendamento</button></>}</>:<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=fields(e.currentTarget);try{const result=await rpc<Charge>('asaas_checkout',{appointment_id:hold.id,payer:f,billingType:f.billingType});setCharge(result);onStarted();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><PayerFields/><label>Forma de pagamento<select name="billingType"><option value="PIX">Pix com confirmação automática</option><option value="CREDIT_CARD">Cartão de crédito</option></select></label><button className="btn" disabled={busy||!accepted}>{busy?'Preparando cobrança…':'Gerar pagamento seguro'}</button><p className="policy-note">Os dados do cartão são preenchidos no Asaas. Pagar após a expiração não garante a reserva do horário.</p></form>}{error&&<p role="alert" className="form-error">{error}</p>}</section>;
}
