'use client';
import {useEffect,useState} from 'react';
import type {FirebaseSalonApi} from '@/shared/firebase-client';
type SalonLink={salonId:string;name?:string;slug?:string;role?:string};
type PublicSalon={id:string;slug:string;name:string;description?:string};
export function PlatformEntry({api,error:initialError,requestedSlug,onSalon}:{api:FirebaseSalonApi;error?:string;requestedSlug?:string;onSalon:(slug:string,view?:'admin')=>void}){
 const[session,setSession]=useState(api.session),[register,setRegister]=useState(false),[createSalon,setCreateSalon]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(initialError||''),[salons,setSalons]=useState<SalonLink[]>([]),[directory,setDirectory]=useState<PublicSalon[]>([]),[search,setSearch]=useState('');
 useEffect(()=>{api.rpc<PublicSalon[]>('salons').then(setDirectory).catch(e=>setError(e.message));},[api]);
 useEffect(()=>{if(session)api.rpc<SalonLink[]>('my_salons').then(setSalons).catch(e=>setError(e.message));},[api,session]);
 const submitAuth=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{if(register)await api.register(String(f.get('email')),String(f.get('password')),String(f.get('name')),String(f.get('phone')));else await api.login(String(f.get('email')),String(f.get('password')));setSession(api.session);if(requestedSlug)onSalon(requestedSlug);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <main className="platform-entry"><div className="platform-entry-brand"><img src="/icons/icon-192.png" alt="" width="72" height="72"/><span>Maison Bella<small>Seu salão. Seu momento.</small></span></div><div className="platform-entry-grid"><section><p className="eyebrow">CUIDADO QUE COMBINA COM VOCÊ</p><h1>{session?'Seu próximo momento começa aqui.':'Todos os seus momentos. Uma só conta.'}</h1><p>{session?'Abra um salão para acompanhar seus horários ou escolha onde será seu próximo cuidado.':'Encontre seu salão, reserve um horário e acompanhe tudo pelo aplicativo.'}</p>{error&&<p role="alert" className="form-error">{error}</p>}{session&&<div className="list-stack"><h2>Meus salões</h2>{salons.filter(s=>s.slug).map(s=><article className="panel" key={s.salonId}><h3>{s.name||s.slug}</h3><div className="button-row"><button className="btn outline" onClick={()=>onSalon(s.slug!)}>Área da cliente</button>{s.role&&['OWNER','MANAGER','RECEPTIONIST','PROFESSIONAL','FINANCE'].includes(s.role)&&<button className="btn" onClick={()=>onSalon(s.slug!,'admin')}>Administrar salão</button>}</div></article>)}{!salons.length&&<p>Seus salões aparecerão aqui após seu primeiro agendamento ou convite da equipe.</p>}<button className="text-btn" onClick={async()=>{setBusy(true);try{await api.logout();setSession(null);setSalons([]);setCreateSalon(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Sair da conta</button></div>}</section>
 <section className="panel">{!session?<><h2>{register?'Criar minha conta':'Entrar na minha conta'}</h2><form key={register?'register':'login'} className="form-stack" onSubmit={submitAuth}>{register&&<><label>Seu nome<input required name="name" autoComplete="name" maxLength={100}/></label><label>Telefone com DDD<input required type="tel" name="phone" autoComplete="tel" minLength={8} maxLength={30}/></label></>}<label>E-mail<input type="email" required name="email" autoComplete="email"/></label><label>Senha<input type="password" required name="password" autoComplete={register?'new-password':'current-password'} minLength={6}/></label><button className="btn" disabled={busy}>{busy?'Aguarde…':register?'Criar conta':'Entrar'}</button></form><button className="text-btn" onClick={()=>setRegister(!register)}>{register?'Já tenho uma conta':'Ainda não tenho conta'}</button><button className="text-btn" onClick={async()=>{const email=prompt('Informe seu e-mail para recuperar a senha:');if(email)try{await api.resetPassword(email);setError('Se houver uma conta para este e-mail, você receberá as instruções.');}catch(e){setError((e as Error).message);}}}>Esqueci minha senha</button></>:<><h2>Você administra um salão?</h2><p>Cadastre seu espaço, configure sua equipe e personalize a experiência das suas clientes.</p><button className="btn outline" onClick={()=>setCreateSalon(v=>!v)}>{createSalon?'Fechar cadastro':'Cadastrar meu salão'}</button>{createSalon&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const result=await api.rpc<{slug:string}>('provision_salon',{name:f.get('name'),slug:f.get('slug'),address:f.get('address'),preset:f.get('preset'),timezone:f.get('timezone')});onSalon(result.slug,'admin');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Nome do salão<input name="name" required minLength={2} maxLength={100}/></label><label>Endereço do link<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" minLength={3} maxLength={60} placeholder="nome-do-seu-salao"/><small>Letras minúsculas, números e hífens.</small></label><label>Endereço para atendimento<input name="address" required maxLength={250}/></label><label>Fuso horário<select name="timezone">{['America/Sao_Paulo','America/Manaus','America/Recife','America/Fortaleza','America/Belem','America/Rio_Branco','America/Cuiaba'].map(z=><option key={z}>{z}</option>)}</select></label><label>Identidade inicial<select name="preset">{['Rose','Champagne','Blossom','Noir','Clean','Lavender','Luxury','Minimal'].map(p=><option key={p}>{p}</option>)}</select></label><button className="btn" disabled={busy}>{busy?'Criando…':'Criar e configurar meu salão'}</button></form>}</>}</section></div>
 <section className="directory-section"><p className="eyebrow">ESCOLHA SEU ESPAÇO DE CUIDADO</p><h2>Encontre um salão</h2><label className="search-field"><input aria-label="Pesquisar salões" placeholder="Busque pelo nome do salão" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="client-grid">{directory.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())).map(s=><button className="selection-row" key={s.id} onClick={()=>onSalon(s.slug)}><span><strong>{s.name}</strong><small>{s.description||'Veja os serviços e horários disponíveis.'}</small></span><span>Abrir →</span></button>)}</div>{!directory.length&&<p>Os salões aparecerão aqui após a publicação. Você também pode acessar o link enviado pelo seu salão.</p>}</section></main>;
}
