'use client';
import {createContext,useContext,useState,useEffect,useCallback,useRef,type ReactNode} from 'react';
import {SalonApi} from '@/shared/client';
import {FirebaseSalonApi} from '@/shared/firebase-client';
import {PlatformEntry} from './platform-entry';
import {PresentationApi} from '@/shared/presentation';
import {themeFor} from '@/shared/theme';
import {readLocal,writeLocal} from '@/shared/local-preferences';
import type {Catalog,Me,Appointment,Session} from '@/shared/types';
type View='home'|'services'|'professionals'|'agenda'|'profile'|'admin'|'benefits'|'routine'|'favorites'|'inspiration';
const views:View[]=['home','services','professionals','agenda','profile','admin','benefits','routine','favorites','inspiration'];
function viewFromUrl():View { const value=new URLSearchParams(location.search).get('view') as View;return views.includes(value)?value:'home'; }
type BookingStart={serviceId?:string;professionalId?:string;reschedule?:Appointment};
type ContextType={api:SalonApi;catalog:Catalog;me:Me|null;session:Session|null;appointments:Appointment[];view:View;go:(v:View)=>void;refresh:()=>Promise<void>;changeSalon:(slug:string)=>void;book:(start?:BookingStart)=>void;booking:BookingStart|null;closeBooking:()=>void;authOpen:boolean;setAuthOpen:(v:boolean)=>void;notice:(text:string)=>void;dark:boolean;setDark:(v:boolean)=>void;};
const Context=createContext<ContextType|null>(null);
export const useSalon=()=>{const c=useContext(Context);if(!c)throw new Error('SalonProvider ausente');return c;};
export function SalonProvider({children}:{children:ReactNode}){
 const [api,setApi]=useState<SalonApi|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[me,setMe]=useState<Me|null>(null),[session,setSession]=useState<Session|null>(null),[appointments,setAppointments]=useState<Appointment[]>([]),[view,setView]=useState<View>('home'),[slug,setSlug]=useState('maison-bella'),[error,setError]=useState(''),[booking,setBooking]=useState<BookingStart|null>(null),[authOpen,setAuthOpen]=useState(false),[toast,setToast]=useState(''),[dark,setDark]=useState(false);
 const refreshVersion=useRef(0);
 useEffect(()=>{const env=import.meta.env;const params=new URLSearchParams(location.search);const live=params.get('mode')==='live'||(params.get('mode')!=='demo'&&env.VITE_FIREBASE_ENABLED==='true');const instance=live?new FirebaseSalonApi():new PresentationApi();setSlug(params.get('salon')||(live?'':readLocal<string>('bella.salon','maison-bella')));setView(viewFromUrl());setDark(readLocal('bella.dark',false));instance.init().then(()=>{setApi(instance);setSession(instance.session);}).catch(e=>setError(e.message));},[]);
 const refresh=useCallback(async()=>{if(!api)return;const version=++refreshVersion.current;try{const next=await api.rpc<Catalog>('catalog',{slug});const [m,a]=api.session?await Promise.all([api.rpc<Me>('me',{salon_id:next.salon.id}),api.rpc<Appointment[]>('appointments',{salon_id:next.salon.id})]):[null,[]];if(version!==refreshVersion.current)return;setCatalog(next);setSession(api.session);setMe(m);setAppointments(a);setError('');}catch(e){if(version===refreshVersion.current)setError((e as Error).message);throw e;}},[api,slug]);
 useEffect(()=>{const sync=()=>{const next=new URLSearchParams(location.search).get('salon');if(next&&next!==slug){refreshVersion.current++;setCatalog(null);setSlug(next);}setView(viewFromUrl());setBooking(null);};window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[slug]);
 useEffect(()=>{if(slug)refresh().catch(()=>{});},[refresh,slug]);
 useEffect(()=>{if(!api||!catalog)return;const handler=()=>{if(document.visibilityState==='visible')refresh().catch(()=>{});};document.addEventListener('visibilitychange',handler);const unwatch=api instanceof FirebaseSalonApi&&session?api.watchAppointments(catalog.salon.id,handler,e=>setError(e.message)):()=>{};return()=>{document.removeEventListener('visibilitychange',handler);unwatch();};},[api,catalog?.salon.id,session?.user.id,refresh]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{const isDark=!!(dark&&catalog?.branding.dark_allowed)||catalog?.branding.preset==='Noir';const t=themeFor(catalog?.branding.preset,catalog?.branding.primary_color,dark&&catalog?.branding.dark_allowed);const root=document.documentElement;for(const[k,v]of Object.entries(t))if(typeof v==='string')root.style.setProperty(`--bella-${k.replace(/[A-Z]/g,x=>'-'+x.toLowerCase())}`,v);root.style.setProperty('--bella-radius',`${t.radius}px`);root.style.setProperty('--bella-heading-font',catalog?.branding.font_style==='Modern'?'Arial, sans-serif':'Georgia, serif');root.style.colorScheme=isDark?'dark':'light';writeLocal('bella.dark',dark);},[catalog?.branding,dark]);
 const changeSalon=(next:string)=>{refreshVersion.current++;setCatalog(null);setAppointments([]);setMe(null);setBooking(null);setSlug(next);writeLocal('bella.salon',next);const url=new URL(location.href);url.pathname='/';url.searchParams.set('salon',next);url.searchParams.delete('view');history.pushState(null,'',url);setView('home');};
 const go=(next:View)=>{setView(next);const url=new URL(location.href);url.searchParams.set('salon',slug);if(next==='home')url.searchParams.delete('view');else url.searchParams.set('view',next);if(url.href!==location.href)history.pushState(null,'',url);window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 if(api instanceof FirebaseSalonApi&&(!slug||(!catalog&&error)))return <PlatformEntry api={api} error={error} requestedSlug={slug} onSalon={next=>{setError('');changeSalon(next);}}/>;
 if(!api||!catalog)return <main className="launch-screen"><img src="/icons/icon-192.png" width="100" height="100" alt="Maison Bella"/><h1>Seu momento começa aqui.</h1>{error?<><p role="alert">{error}</p><button className="btn" onClick={()=>api?refresh().catch(()=>{}):location.reload()}>Tentar novamente</button></>:<><div className="loading-line"/><p>Preparando seu espaço de cuidado…</p></>}</main>;
 return <Context.Provider value={{api,catalog,me,session,appointments,view,go,refresh,changeSalon,book:(s={})=>setBooking(s),booking,closeBooking:()=>setBooking(null),authOpen,setAuthOpen,notice:setToast,dark,setDark}}>{children}{toast&&<div className="toast" role="status">{toast}</div>}{error&&<div className="connection-error" role="alert">{error}<button onClick={()=>refresh().catch(()=>{})}>Reconectar</button></div>}</Context.Provider>;
}
