'use client';
import {useState} from 'react';
import {Check,Palette,ImagePlus,Plus,Trash2} from 'lucide-react';
import {useSalon} from './provider';
import {FirebaseSalonApi} from '@/shared/firebase-client';
import {presets,themeFor} from '@/shared/theme';
import type {Branding,Schedule,Unit} from '@/shared/types';
export type Save=(action:string,payload:Record<string,unknown>)=>Promise<void>;

export function ImageField({label,value,onChange,onBusy}:{label:string;value:string;onChange:(v:string)=>void;onBusy?:(v:boolean)=>void}){
 const{api,catalog}=useSalon();const[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="image-field"><label>{label}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file||!(api instanceof FirebaseSalonApi))return;setBusy(true);onBusy?.(true);setError('');try{onChange(await api.uploadBranding(catalog.salon.id,file));}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy?.(false);}}}/></label>{value?<div className="image-field-preview"><img src={value} alt={label}/><button type="button" className="text-btn" onClick={()=>onChange('')}>Remover imagem</button></div>:<small><ImagePlus size={16}/> PNG, JPEG ou WebP, até 5 MB.</small>}{busy&&<p role="status">Enviando imagem… Aguarde antes de salvar.</p>}{error&&<p role="alert" className="form-error">{error}</p>}</div>;
}

export function IdentitySettings({save}:{save:Save}){
 const{catalog}=useSalon();const[b,setB]=useState<Branding>({...catalog.branding}),[name,setName]=useState(catalog.salon.name),[uploading,setUploading]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const change=(key:keyof Branding,v:string|boolean)=>setB(x=>({...x,[key]:v}));
 const theme=themeFor(b.preset,b.primary_color,false,b);
 return <div className="settings-layout"><section className="panel"><h2>Identidade do salão</h2><p>Personalize o que suas clientes veem, desde o cabeçalho até a reserva.</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{await save('admin_branding',{...b,name,primary_color:b.primary_color||''});setMessage('Identidade publicada no salão.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>
 <label>Nome do salão<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label>
 <div className="preset-grid">{Object.entries(presets).map(([key,t])=><button type="button" className={`preset-card ${b.preset===key?'selected':''}`} key={key} aria-pressed={b.preset===key} onClick={()=>setB(v=>({...v,preset:key,primary_color:'',secondary_color:'',accent_color:'',background_color:''}))}><span className="swatches">{[t.primary,t.secondary,t.accent].map(c=><i key={c} style={{background:c}}/>)}</span><strong>{key}</strong>{b.preset===key&&<Check size={16}/>}</button>)}</div>
 <div className="color-grid">{([['primary_color','Cor principal','primary'],['secondary_color','Cor secundária','secondary'],['accent_color','Destaques','accent'],['background_color','Fundo','background']] as const).map(([key,label,palette])=><label key={key}>{label}<div className="color-input"><input type="color" aria-label={label} value={b[key]||theme[palette]} onChange={e=>change(key,e.target.value)}/><input aria-label={`${label} hexadecimal`} pattern="#[0-9a-fA-F]{6}" value={b[key]||''} placeholder={theme[palette]} onChange={e=>change(key,e.target.value)}/></div></label>)}</div>
 <label>Tipografia<select value={b.font_style} onChange={e=>change('font_style',e.target.value)}><option value="Editorial">Editorial · com serifa</option><option value="Modern">Moderna · sem serifa</option></select></label>
 <label className="switch-row">Permitir modo escuro<input type="checkbox" checked={b.dark_allowed} onChange={e=>change('dark_allowed',e.target.checked)}/></label>
 <ImageField onBusy={setUploading} label="Logo do salão" value={b.logo_url||''} onChange={v=>change('logo_url',v)}/><ImageField onBusy={setUploading} label="Imagem de capa" value={b.cover_url||''} onChange={v=>change('cover_url',v)}/>
 <label>Título da página inicial<input maxLength={120} value={b.hero_title||''} onChange={e=>change('hero_title',e.target.value)} placeholder="Seu cuidado. Seu ritmo. Seu momento."/></label>
 <label>Mensagem da página inicial<textarea maxLength={300} value={b.hero_subtitle||''} onChange={e=>change('hero_subtitle',e.target.value)} placeholder="Pequenos rituais que fazem você se sentir ainda mais você."/></label>
 <button className="btn" disabled={busy||uploading}><Palette size={17}/>{busy?'Salvando…':'Salvar identidade'}</button>{message&&<p role="status">{message}</p>}
 </form></section><aside className="settings-preview"><div className="salon-phone" style={{background:theme.background,color:theme.text}}>{b.logo_url&&<img className="salon-phone-logo" src={b.logo_url} alt="Prévia da logo"/>}<strong>{name}</strong>{b.cover_url&&<img className="salon-phone-cover" src={b.cover_url} alt="Prévia da capa"/>}<h3 style={{fontFamily:b.font_style==='Modern'?'Arial, sans-serif':'Georgia, serif'}}>{b.hero_title||'Seu cuidado. Seu momento.'}</h3><p>{b.hero_subtitle||'Um espaço de cuidado só seu.'}</p><span style={{background:theme.primary,color:theme.onPrimary}}>Agendar meu cuidado</span><small>Prévia · salve para aplicar</small></div><p className="policy-note">A logo identifica seu salão dentro da plataforma. O ícone do PWA identifica o aplicativo compartilhado entre os salões.</p></aside></div>;
}

export const defaultSchedule:Schedule={opens:'09:00',closes:'19:00',weekdays:[1,2,3,4,5,6],breaks:[]};
export function ScheduleFields({value,onChange}:{value:Schedule;onChange:(v:Schedule)=>void}){
 return <fieldset className="schedule-fields"><legend>Horários de atendimento</legend><div className="form-columns"><label>Abertura<input type="time" required value={value.opens} onChange={e=>onChange({...value,opens:e.target.value})}/></label><label>Encerramento<input type="time" required value={value.closes} onChange={e=>onChange({...value,closes:e.target.value})}/></label></div><div className="weekday-options">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((label,i)=><label key={i}><input type="checkbox" checked={value.weekdays.includes(i)} onChange={e=>onChange({...value,weekdays:e.target.checked?[...value.weekdays,i]:value.weekdays.filter(d=>d!==i)})}/>{label}</label>)}</div><p>Intervalos (almoço, descanso)</p>{value.breaks.map((b,i)=><div className="break-row" key={i}><label>Início<input type="time" aria-label={`Início do intervalo ${i+1}`} value={b.start} required onChange={e=>onChange({...value,breaks:value.breaks.map((v,n)=>n===i?{...v,start:e.target.value}:v)})}/></label><label>Fim<input type="time" aria-label={`Fim do intervalo ${i+1}`} value={b.end} required onChange={e=>onChange({...value,breaks:value.breaks.map((v,n)=>n===i?{...v,end:e.target.value}:v)})}/></label><button type="button" className="icon-btn" aria-label={`Remover intervalo ${i+1}`} onClick={()=>onChange({...value,breaks:value.breaks.filter((_,n)=>n!==i)})}><Trash2 size={18}/></button></div>)}<button type="button" className="text-btn" disabled={value.breaks.length>=5} onClick={()=>onChange({...value,breaks:[...value.breaks,{start:'12:00',end:'13:00'}]})}><Plus size={16}/>Adicionar intervalo</button></fieldset>;
}

export function SalonSettings({save}:{save:Save}){
 const{catalog,notice,refresh}=useSalon();const[description,setDescription]=useState(catalog.salon.description||''),[unit,setUnit]=useState<Unit|true|null>(null),[busy,setBusy]=useState(false);
 return <div className="list-stack"><section className="panel"><h2>Sobre o salão</h2><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await save('admin_info',{description});}catch(e){notice((e as Error).message);}finally{setBusy(false);}}}><label>Apresentação<textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="btn" disabled={busy}>Salvar apresentação</button></form></section><section className="panel"><div className="section-heading"><h2>Unidades e funcionamento</h2><button className="btn outline" onClick={()=>setUnit(true)}>Adicionar unidade</button></div>{catalog.units.map(u=><button className="selection-row full" key={u.id} onClick={()=>setUnit(u)}><span><strong>{u.name}</strong><small>{u.address} · {u.timezone}</small><small>{u.schedule?.opens}–{u.schedule?.closes}</small></span><span>Editar</span></button>)}{unit&&<UnitEditor key={unit===true?'new':unit.id} value={unit===true?undefined:unit} save={save} close={()=>setUnit(null)}/>}</section><section className="panel"><h2>Disponibilidade do salão</h2><p>{catalog.published?'Seu link está aberto para reservas.':'Seu salão está em preparação e pode ser configurado pela administração.'}</p><button className="btn outline" disabled={busy} onClick={async()=>{setBusy(true);try{await save(catalog.published?'unpublish_salon':'publish_salon',{});await refresh();}catch(e){notice((e as Error).message);}finally{setBusy(false);}}}>{catalog.published?'Pausar novas reservas':'Publicar salão'}</button><p className="policy-note">Pausar mantém os agendamentos existentes. A administração continua acessível.</p></section></div>;
}
function UnitEditor({value,save,close}:{value?:Unit;save:Save;close:()=>void}){
 const[schedule,setSchedule]=useState(value?.schedule||defaultSchedule),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <form className="form-stack inset-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await save('admin_unit',{id:value?.id,name:f.get('name'),address:f.get('address'),timezone:f.get('timezone'),schedule});close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h3>{value?'Editar unidade':'Nova unidade'}</h3><label>Nome da unidade<input name="name" required defaultValue={value?.name}/></label><label>Endereço<input name="address" required maxLength={250} defaultValue={value?.address}/></label><label>Fuso horário<select name="timezone" defaultValue={value?.timezone||'America/Sao_Paulo'}>{['America/Sao_Paulo','America/Manaus','America/Recife','America/Fortaleza','America/Belem','America/Rio_Branco','America/Cuiaba'].map(v=><option key={v}>{v}</option>)}</select></label><ScheduleFields value={schedule} onChange={setSchedule}/>{error&&<p className="form-error" role="alert">{error}</p>}<div className="button-row"><button className="btn" disabled={busy}>Salvar unidade</button><button type="button" className="text-btn" onClick={close}>Cancelar</button></div></form>;
}
